### ISSUE TITLE
Broken depends for Ubuntu 14.10 on ppa

### ISSUE THREAD

**Issue by freeniki** [xylosper/bomi#175]
The following packages have unmet dependencies :
cmplayer: Depends : libqt5qml-quickcontrols but it can not be installed
Recommends : YouTube -DL but it will not be installed
E: Unable to correct problems , you have delayed (held ) broken packages .

Please see this fix:
http://pastebin.com/n0LQZLwY

Because ibqt5qml-quickcontrols renamed to qml-module-qtquick-controls on Ubuntu 14.10

**Comment by xylosper** [comment]
I'll release new version in couple of days as bomi.

**Comment by ahjolinna** [comment]
@xylosper: with a new logo ? ;)   did u get the new logo suggestions/ideas?

**Comment by freeniki** [comment]
![default](https://cloud.githubusercontent.com/assets/8083855/5788118/26965f42-9e36-11e4-9e09-190f59e7a9ec.png)

**Comment by xylosper** [comment]
Oh, the logo is decided. You'll see it in next version. Thank you for attention.

**Comment by ahjolinna** [comment]
@xylosper : I like the new one, I'm already using it

**Comment by xylosper** [comment]
Fixed new package is uploaded in bomi PPA. Thank you.

**Comment by freeniki** [comment]
New logo very cool!!! Thx for ppa :)

**Comment by dzikitomek** [comment]
I still have this issue while using bomi PPA on Mint Linux 17.1 (based on ubuntu 14.04). 
Is there any chance this was fixed just for 14.10 and not 14.04?

**Comment by xylosper** [comment]
Of course this is only for 14.10. 14.04 doesn't have any problem.

**Comment by dzikitomek** [comment]
@xylosper : Thanks for quick reply, but it seems it does not work on 14.04 in my case.

It always complains about beeing unable to install libqt5qml-quickcontrols and qtdeclarative5-quicklayouts-plugin.

I have gathered some more system info, ppa info etc. here: http://wklej.org/id/1706897/

At this point I'm out of ideas but this situation seem very similar to what happened to @varlesh. It did worked a few months ago on the same system but it broke after an upgrade.

**Comment by xylosper** [comment]
I don't understand your language. Please post log in english.
Before running any command, first run next to set locale to english:
```
$ export LC_ALL=C
```

**Comment by dzikitomek** [comment]
Sure. Once again:

http://wklej.org/hash/4a5422ffbf2/

**Comment by xylosper** [comment]
Why did you try to install `qtbase-abi-5-2-1 qtdeclarative-abi-5-2-1` ?

**Comment by dzikitomek** [comment]
In desperation I tried to install libqt5qml-quickcontrols and qtdeclarative5-quicklayouts-plugin manually and these were "unmet dependencies" that poped up. 

```
blackbox ~ # export LC_ALL=C; apt-get install qtdeclarative5-quicklayouts-plugin                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtdeclarative5-quicklayouts-plugin : Depends: qtdeclarative-abi-5-2-1
E: Unable to correct problems, you have held broken packages.
```

**Comment by xylosper** [comment]
Please try
```
$ sudo apt-get install libqt5core5a
$ sudo apt-get install libqt5qml5
```

**Comment by dzikitomek** [comment]
These packages are already installed.


```
blackbox ~ # export LC_ALL=C; sudo apt-get install libqt5core5a
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5core5a is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


blackbox ~ # export LC_ALL=C; sudo apt-get install libqt5qml5  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5qml5 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
blackbox ~ # export LC_ALL=C; sudo apt-get install libqt5core5a
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5core5a is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
blackbox ~ # export LC_ALL=C; sudo apt-get install libqt5qml5  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5qml5 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by xylosper** [comment]
what says `apt-cache show libqt5qml5` and `apt-cache show libqt5core5a`?

**Comment by xylosper** [comment]
Btw, you've done update & upgrade already, right?

**Comment by dzikitomek** [comment]
Yes, sure, multiple times. Both upgrade and dist-upgrade. As I mentioned it started few months ago, I though it's a temporary issue and just waited for new package but there was no change till today :)

apt-cache show: http://wklej.org/hash/912a9900444/

**Comment by xylosper** [comment]
Your Qt version is 5.3 which is not provided by Ubuntu 14.04.

**Comment by dzikitomek** [comment]
So it's upgraded becouse of some other PPA's? Or rather issue in mint itself?

**Comment by xylosper** [comment]
Have you installed MuseScore? It seems the PPA for MuseScore contains `5.3.0-3ubuntu13~trusty1` which is not an official version.

**Comment by dzikitomek** [comment]
Yes, I did. I had their PPA enabled. Now I have disabled it, removed musescore, did update and upgrade. Not sure what should be the next step, though.

I also have another big music PPA, kxstudio.

**Comment by xylosper** [comment]
Try aptitude not apt-get:
```
$ sudo aptitude install bomi
```

**Comment by dzikitomek** [comment]
@xylosper thank you for your patience! Thanks to you and aptitude Bomi is up and running:

![image](https://cloud.githubusercontent.com/assets/12369167/7550225/fb27376a-f659-11e4-9918-3955ba317c11.png)

Aptitude was more clever, one of proposed suggestions was to downgrade a bunch of QT packages from 5.3 to 5.2 and then install bomi. It worked well and so far I don't see any impact on the rest of my OS.

Solution I chose:

```
Accept this solution? [Y/n/q/?] n
The following actions will resolve these dependencies:

      Remove the following packages:                                                                        
1)      libqt5quickwidgets5                                                                                 
2)      qml-module-qtquick2                                                                                 

      Install the following packages:                                                                       
3)      libqt5positioning5 [5.2.1-1ubuntu2 (now, trusty)]                                                   
4)      libqt5sensors5 [5.2.1+dfsg-2ubuntu2 (now, trusty)]                                                  

      Downgrade the following packages:                                                                     
5)      libqt5clucene5 [5.3.0-5~trusty1 (now) -> 5.2.1-8build1 (trusty)]   
(...)
```

More log: http://wklej.org/hash/96c7a5af81a/

Thanks again :)

**Comment by xylosper** [comment]
Yeah, `aptitude` handles dependecy problem better than `apt-get`.

If you want to keep using MuseScore, you'd better tell them not to break versioning rule for PPA and not to override system critical library partially.
They should've provided full update for Qt 5.3 if they wanted to override Qt but they only updated partial pacakges they needed, which resulted in breaking of dependencies.
Futhermore, the non-standard versioning for PPA package made it harder to find the problem.

**Comment by dzikitomek** [comment]
Thanks, I will do exactly that.

Meanwhile back to enjoying video content using Bomi, best player around :)
