### ISSUE TITLE
.ass not displayed

### ISSUE THREAD

**Issue by caixiaLU** [xylosper/bomi#368]
Hello,

I usually use <a href=http://pas-bien.net/2srt2ass/ >this</a> site to merge 2 srt files in one .ass file so I can play the movie with well formatted (multiple) subs (example <a href=http://pl.vc/4791u>here</a>). It works fine with vlc or plex but bomi does not display them.

In my log file I found this :

(D)[mpv/ad] Opening audio decoder lavc:dca
(D)[mpv/ad] Requesting 1 threads for decoding.
(D)[mpv/ad] Selected audio codec: DCA (DTS Coherent Acoustics) [lavc:dca]
(D)[mpv/global] config path: 'fonts' -> '(NULL)'
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
(I)[mpv/libass] Bad timestamp
...

Regarding <a href=https://github.com/mpv-player/mpv/issues/1654>this</a> post it seems that the problem come from the sub parser.

<a href=http://ovh.to/VxNXr6>Here</a> is an example of file where the problem occurs.

**Comment by xylosper** [comment]
It's already fixed in libass 0.12.2 which is released ten days ago.
What distro do you use?

**Comment by caixiaLU** [comment]
Thanks for the answer. I'm using Ubuntu 15.04, I updated libass to 0.12.2-1 from  <a href=https://launchpad.net/ubuntu/+source/libass>here</a> but it is still not working. 
Is there something else to do?

**Comment by xylosper** [comment]
For Ubuntu based distro, because the official package is outdated, so PPA in bomi uses its own libass package, so you have to wait till I update it.

**Comment by caixiaLU** [comment]
OK no problem, thanks for the help.

**Comment by xylosper** [comment]
New version updated. Can you try it?

**Comment by caixiaLU** [comment]
Works fine, thank your very much.

**Comment by xylosper** [comment]
Thank you for testing.
